Reshuffle docs/ versions/ and ush/ contents - release/satingest.v4.2.1_RM
NOAA-EMC/satingest pull request #18
Opened 2022-09-26 18:55 UTC by ilianagenkova

-move build.sh from top level dir to ush/
-move VERSION to versions/
-renamed release_notes/ to docs/ 
-moved README.md to docs/
-updated Release_Notes.txt, CMakeLists.txt, build.sh and README.md

2022-09-26 19:24 UTC, SteveStegall-NOAA reviewed
Looks good to me.  Thanks.

2022-09-26 21:23 UTC, aerorahul requested changes
A couple of requested changes.

2022-09-26 21:23 UTC, aerorahul commented on ush/CMakeLists.txt
> +  build.sh
This should not be installed.

2022-09-26 21:23 UTC, aerorahul commented on docs/Release_Notes.txt
>   A release_notes/CMakeLists.txt
Please remove this `CMakeLists.txt`.

2022-09-26 21:23 UTC, aerorahul commented on ush/build.sh
> +#pkg_root=`dirname $(readlink -f $0)`
remove commented lines.

2022-09-28 17:09 UTC, ilianagenkova commented on docs/Release_Notes.txt
>   A release_notes/CMakeLists.txt
This line moved as a line number.

2022-09-28 17:11 UTC, ilianagenkova commented
@SteveStegall-NOAA and @aerorahul , I can't close the PR unless one of you approves the PR. could you do that? thanks

2022-09-28 17:13 UTC, aerorahul approved these changes
changes look good.
Thank you for including suggested reviews

2022-09-30 01:28 UTC, merged