Release/satingest.v4.1.0
NOAA-EMC/satingest pull request #9
Opened 2022-05-10 17:03 UTC by ShelleyMelchior-NOAA

Please review merge of `release/satingest.v1.4.0` into `develop`. `release/satingest.v4.1.0` is what NCO is running in para on dogwood and cactus. The para has been running successfully for quite some time, so it is time to merge into `develop`.

2022-05-10 20:14 UTC, SteveStegall-NOAA approved these changes

2022-05-12 02:02 UTC, ilianagenkova requested changes
@ShelleyMelchior-NOAA ,
I left a couple of comments/questions , just to clarify what we need to clean up w.r.t. hms data.

I am not a satingest expert, so as sanity check I'll try compiling the code  before approving/merging this PR. I will try to wrap it up in a day or two. thanks!

2022-05-12 02:02 UTC, ilianagenkova commented on fix/aerosol
> +# No longer needed for WCOSS2 because downstream application,
@ShelleyMelchior-NOAA , do you mean we could remove lines 42-53 and fix/aerosol.hms_smoke_prelim ?

2022-05-12 02:02 UTC, ilianagenkova commented on fix/aerosol
> +# No longer needed for WCOSS2 because downstream application,
Save question as before, do you imply we remove lines 58-87 along with fix/aerosol.hms_smoke_final from the satingest s/w suite?

2022-05-12 20:20 UTC, ilianagenkova approved these changes

2022-05-12 20:21 UTC, merged

2022-05-12 20:26 UTC, ilianagenkova commented
@SudhirNadiga-NOAA  I made you a reviewer just for awareness.

All, I found GitHub Issue #8 (thanks, @ShelleyMelchior-NOAA !). It documents well what needs to be cleaned in the satingest code shortly after WCOSS2-golive . I approved this PR, but will keep the GitHub issue open, to remind us what we need to do later on. This is a regular practice on GitHub - open issues document what is still in the works.

2022-05-17 16:03 UTC, ShelleyMelchior-NOAA commented
Excellent -- thank you @ilianagenkova